# Generated by Django 4.2.7 on 2023-12-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_task_created_at_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_spent',
            field=models.IntegerField(default=0),
        ),
    ]
