# Generated by Django 4.2.7 on 2023-12-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_task_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.JSONField(default=list),
        ),
    ]
