# Generated by Django 4.2.7 on 2024-01-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_task_end_date_task_start_date_alter_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_date',
        ),
    ]
