# Generated by Django 4.2.7 on 2024-02-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_task_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='time_spent',
        ),
        migrations.AddField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
